CREATE SEQUENCE seq_kategoriak START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_termek START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_history START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE seq_filmek START WITH 10000 INCREMENT BY 1;
CREATE SEQUENCE seq_vetitesek START WITH 10000 INCREMENT BY 1;
CREATE SEQUENCE seq_ugyfelek START WITH 10000 INCREMENT BY 1;
CREATE SEQUENCE seq_jegyek START WITH 10000 INCREMENT BY 1;
