CREATE SEQUENCE seq_kategoria START WITH 1;
CREATE SEQUENCE seq_terem START WITH 1;
CREATE SEQUENCE seq_film START WITH 10000;
CREATE SEQUENCE seq_vetites START WITH 10000;
CREATE SEQUENCE seq_ugyfel START WITH 10000;
CREATE SEQUENCE seq_jegy START WITH 10000;
CREATE SEQUENCE seq_hiba START WITH 1;
